# Generated by Django 5.2.4 on 2025-07-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servico_ativo_usuario_email_verificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ da oficina', max_length=18),
        ),
        migrations.AddField(
            model_name='profissional',
            name='endereco',
            field=models.TextField(blank=True, help_text='Endereço da oficina'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='nome_oficina',
            field=models.CharField(blank=True, help_text='Nome da oficina (se aplicável)', max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_oficina',
            field=models.BooleanField(default=False),
        ),
    ]
