# Generated by Django 5.2.4 on 2025-07-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profissional_cnpj_profissional_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aprovado_pendente',
            field=models.BooleanField(default=False, help_text='Aguardando aprovação do administrador'),
        ),
    ]
