# Generated by Django 5.2.4 on 2025-07-27 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_aprovado_pendente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.TextField()),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('site', models.URLField(blank=True)),
                ('cnpj', models.CharField(max_length=18)),
                ('aprovado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
                'db_table': 'oficinas',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['profissional__oficina', 'usuario__username', '-data'], 'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='codigoverificacao',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Código de Verificação', 'verbose_name_plural': 'Códigos de Verificação'},
        ),
        migrations.AlterModelOptions(
            name='manutencao',
            options={'ordering': ['veiculo__placa', 'data'], 'verbose_name': 'Manutenção', 'verbose_name_plural': 'Manutenções'},
        ),
        migrations.AlterModelOptions(
            name='profissional',
            options={'ordering': ['oficina', 'especialidade'], 'verbose_name': 'Profissional', 'verbose_name_plural': 'Profissionais'},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['nome'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['marca', 'modelo', 'placa'], 'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='nome_oficina',
        ),
        migrations.AlterModelTable(
            name='avaliacao',
            table='avaliacoes',
        ),
        migrations.AlterModelTable(
            name='codigoverificacao',
            table='codigo_verificacao',
        ),
        migrations.AlterModelTable(
            name='manutencao',
            table='manutencoes',
        ),
        migrations.AlterModelTable(
            name='profissional',
            table='profissionais',
        ),
        migrations.AlterModelTable(
            name='servico',
            table='servicos',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
        migrations.AlterModelTable(
            name='veiculo',
            table='veiculos',
        ),
        migrations.AddField(
            model_name='profissional',
            name='oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='core.oficina'),
        ),
    ]
