# Generated by Django 5.2.4 on 2025-07-29 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_oficina_alter_avaliacao_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria do Checklist',
                'verbose_name_plural': 'Categorias do Checklist',
                'db_table': 'categorias_checklist',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Veículo',
                'verbose_name_plural': 'Tipos de Veículos',
                'db_table': 'tipos_veiculos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do checklist (ex: Checklist Preventiva Carros)', max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='core.oficina')),
                ('tipo_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='core.tipoveiculo')),
            ],
            options={
                'verbose_name': 'Checklist',
                'verbose_name_plural': 'Checklists',
                'db_table': 'checklists',
                'ordering': ['oficina__nome', 'tipo_veiculo__nome', 'nome'],
                'unique_together': {('oficina', 'tipo_veiculo', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo_verificacao', models.CharField(choices=[('visual', 'Verificação Visual'), ('teste', 'Teste Funcional'), ('medicao', 'Medição'), ('inspecao', 'Inspeção Detalhada')], default='visual', max_length=20)),
                ('critico', models.BooleanField(default=False, help_text='Item crítico para segurança')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem dentro da categoria')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.categoriachecklist')),
            ],
            options={
                'verbose_name': 'Item do Checklist',
                'verbose_name_plural': 'Itens do Checklist',
                'db_table': 'itens_checklist',
                'ordering': ['categoria__ordem', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemChecklistPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo_verificacao', models.CharField(choices=[('visual', 'Verificação Visual'), ('teste', 'Teste Funcional'), ('medicao', 'Medição'), ('inspecao', 'Inspeção Detalhada')], default='visual', max_length=20)),
                ('critico', models.BooleanField(default=False)),
                ('obrigatorio', models.BooleanField(default=True, help_text='Item obrigatório no checklist')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriachecklist')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_personalizados', to='core.checklist')),
                ('item_padrao', models.ForeignKey(blank=True, help_text='Item padrão do sistema (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.itemchecklist')),
            ],
            options={
                'verbose_name': 'Item Personalizado do Checklist',
                'verbose_name_plural': 'Itens Personalizados do Checklist',
                'db_table': 'itens_checklist_personalizados',
                'ordering': ['checklist', 'categoria__ordem', 'ordem', 'nome'],
            },
        ),
    ]
