# Generated by Django 5.2.4 on 2025-07-29 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_categoriachecklist_tipoveiculo_checklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriachecklist',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_checklist', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checklists_atualizados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemchecklist',
            name='obrigatorio',
            field=models.BooleanField(default=True, help_text='Item obrigatório no checklist'),
        ),
        migrations.AddField(
            model_name='itemchecklist',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itens_checklist', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoveiculo',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_veiculos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChecklistExecutado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_executado', to='core.checklist')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_executado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checklist Executado',
                'verbose_name_plural': 'Checklists Executados',
                'db_table': 'checklist_executado',
                'ordering': ['checklist', 'data_execucao'],
            },
        ),
        migrations.CreateModel(
            name='ItemChecklistExecutado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('resultado', models.CharField(max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('checklist_executado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_checklist_executado', to='core.checklistexecutado')),
                ('item_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_checklist_executado', to='core.itemchecklist')),
            ],
            options={
                'verbose_name': 'Item Checklist Executado',
                'verbose_name_plural': 'Itens Checklist Executados',
                'db_table': 'itens_checklist_executado',
                'ordering': ['checklist_executado', 'item_checklist', 'resultado'],
            },
        ),
        migrations.CreateModel(
            name='Arquivos_checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('documento', 'Documento')], max_length=200)),
                ('item_checklist_executado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_checklist', to='core.itemchecklistexecutado')),
            ],
            options={
                'verbose_name': 'Arquivo Checklist',
                'verbose_name_plural': 'Arquivos Checklist',
                'db_table': 'arquivos_checklist',
                'ordering': ['item_checklist_executado', 'arquivo'],
            },
        ),
    ]
