# Generated by Django 5.2.4 on 2025-07-29 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_categoriachecklist_usuario_checklist_created_by_and_more'),
    ]

    operations = [
    ]
