# Generated by Django 5.2.4 on 2025-07-29 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20250729_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistexecutado',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='checklistexecutado',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('executado', 'Executado'), ('cancelado', 'Cancelado')], default='pendente', max_length=200),
        ),
        migrations.AddField(
            model_name='checklistexecutado',
            name='veiculo',
            field=models.ForeignKey(default=1, help_text='Veículo que está sendo verificado', on_delete=django.db.models.deletion.CASCADE, related_name='checklists_executados', to='core.veiculo'),
            preserve_default=False,
        ),
    ]
