# Generated by Django 5.2.4 on 2025-07-29 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_checklistexecutado_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistexecutado',
            name='veiculo',
            field=models.ForeignKey(blank=True, help_text='Veículo que está sendo verificado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists_executados', to='core.veiculo'),
        ),
    ]
