# Generated by Django 5.2.4 on 2025-08-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_itemchecklistpersonalizado_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemchecklist',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Item do Checklist', 'verbose_name_plural': 'Itens do Checklist'},
        ),
        migrations.AlterModelOptions(
            name='itemchecklistexecutado',
            options={'ordering': ['checklist_executado', 'item_checklist__ordem', 'resultado'], 'verbose_name': 'Item Checklist Executado', 'verbose_name_plural': 'Itens Checklist Executados'},
        ),
    ]
