# Generated by Django 5.2.4 on 2025-08-22 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_itemchecklist_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemchecklistexecutado',
            name='checked',
        ),
        migrations.AlterField(
            model_name='arquivos_checklist',
            name='item_checklist_executado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='core.itemchecklistexecutado'),
        ),
        migrations.AlterField(
            model_name='itemchecklistexecutado',
            name='checklist_executado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_executados', to='core.checklistexecutado'),
        ),
        migrations.AlterField(
            model_name='itemchecklistexecutado',
            name='item_checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_checklist_executados', to='core.itemchecklistpersonalizado'),
        ),
        migrations.AlterField(
            model_name='itemchecklistexecutado',
            name='resultado',
            field=models.CharField(choices=[('1', 'OK'), ('2', 'Atenção'), ('3', 'Problema'), ('4', 'Pendente')], default='4', max_length=200),
        ),
    ]
