# Generated by Django 5.2.4 on 2025-08-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_itemchecklistexecutado_checked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchecklist',
            name='tipo_resultado',
            field=models.CharField(choices=[('1', 'Status'), ('2', 'Valor')], default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='itemchecklist',
            name='valor_resultado',
            field=models.CharField(choices=[('1', 'Numero'), ('2', 'Texto')], default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='itemchecklistexecutado',
            name='valor_resultado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
