# Generated by Django 5.2.4 on 2025-08-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_itemchecklist_tipo_resultado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemchecklist',
            name='tipo_resultado',
            field=models.CharField(choices=[('1', 'Status'), ('2', 'Valor')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='itemchecklistexecutado',
            name='resultado',
            field=models.CharField(choices=[('1', 'OK'), ('2', 'Atenção'), ('3', 'Problema'), ('4', 'Pendente')], default='4', max_length=10),
        ),
        migrations.AlterField(
            model_name='itemchecklistexecutado',
            name='valor_resultado',
            field=models.CharField(blank=True, default=0, max_length=200),
            preserve_default=False,
        ),
    ]
