# Generated by Django 5.2.4 on 2025-08-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_itemchecklist_valor_resultado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemchecklist',
            name='tipo_dado',
            field=models.CharField(choices=[('1', 'Numero'), ('2', 'Texto')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='itemchecklist',
            name='tipo_resultado',
            field=models.CharField(choices=[('1', 'Status'), ('2', 'Valor')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='itemchecklistexecutado',
            name='resultado',
            field=models.CharField(choices=[('1', 'OK'), ('2', 'Atenção'), ('3', 'Problema'), ('4', 'Pendente')], default='4', max_length=10),
        ),
    ]
