# Generated by Django 5.2.4 on 2025-08-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_itemchecklist_tipo_dado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='nome',
            field=models.CharField(help_text='Nome do checklist (ex: Checklist Preventiva Carros)', max_length=50),
        ),
        migrations.AlterField(
            model_name='checklistexecutado',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('executado', 'Executado'), ('cancelado', 'Cancelado')], default='pendente', max_length=30),
        ),
        migrations.AlterField(
            model_name='itemchecklistexecutado',
            name='resultado',
            field=models.CharField(choices=[('1', 'OK'), ('2', 'Atenção'), ('3', 'Problema'), ('4', 'Pendente')], default='4', max_length=10),
        ),
    ]
