# Generated by Django 5.2.4 on 2025-08-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_checklist_nome_alter_checklistexecutado_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivos_checklist',
            name='tipo',
            field=models.CharField(choices=[('foto', 'Foto'), ('documento', 'Documento')], max_length=30),
        ),
        migrations.AlterField(
            model_name='categoriachecklist',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='itemchecklist',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='nome',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='especialidade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tipoveiculo',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
