# Generated by Django 5.2.4 on 2025-08-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_arquivos_checklist_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficina',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_admin_oficina',
            field=models.BooleanField(default=False),
        ),
    ]
