# Generated by Django 5.2.4 on 2025-08-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_oficina_usuario_usuario_is_admin_oficina'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='numero_usuarios',
            field=models.IntegerField(default=2),
        ),
    ]
