# Generated by Django 5.2.4 on 2025-08-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_oficina_numero_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriachecklist',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='nome',
            field=models.CharField(help_text='Nome do checklist (ex: Checklist Preventiva Carros)', max_length=200),
        ),
        migrations.AlterField(
            model_name='itemchecklist',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='especialidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipoveiculo',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
