# Generated by Django 5.2.4 on 2025-08-24 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_categoriachecklist_nome_alter_checklist_nome_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checklist',
            unique_together={('oficina', 'tipo_veiculo')},
        ),
    ]
